# Generated by Django 2.2.12 on 2020-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20200407_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
