# Generated by Django 2.2.12 on 2020-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20200407_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
