# Generated by Django 2.2.12 on 2020-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_commit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
