# Generated by Django 2.2.12 on 2020-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_hooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
